// This file is @generated by prost-build.
/// CounterpartyInfo defines the key that the counterparty will use to message our client
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CounterpartyInfo {
    /// merkle prefix key is the prefix that ics provable keys are stored under
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub merkle_prefix: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// client identifier is the identifier used to send packet messages to our client
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
}
impl ::prost::Name for CounterpartyInfo {
    const NAME: &'static str = "CounterpartyInfo";
    const PACKAGE: &'static str = "ibc.core.client.v2";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.core.client.v2.CounterpartyInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.core.client.v2.CounterpartyInfo".into()
    }
}
/// MsgRegisterCounterparty defines a message to register a counterparty on a client
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgRegisterCounterparty {
    /// client identifier
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    /// counterparty merkle prefix
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub counterparty_merkle_prefix: ::prost::alloc::vec::Vec<
        ::prost::alloc::vec::Vec<u8>,
    >,
    /// counterparty client identifier
    #[prost(string, tag = "3")]
    pub counterparty_client_id: ::prost::alloc::string::String,
    /// signer address
    #[prost(string, tag = "4")]
    pub signer: ::prost::alloc::string::String,
}
impl ::prost::Name for MsgRegisterCounterparty {
    const NAME: &'static str = "MsgRegisterCounterparty";
    const PACKAGE: &'static str = "ibc.core.client.v2";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.core.client.v2.MsgRegisterCounterparty".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.core.client.v2.MsgRegisterCounterparty".into()
    }
}
/// MsgRegisterCounterpartyResponse defines the Msg/RegisterCounterparty response type.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgRegisterCounterpartyResponse {}
impl ::prost::Name for MsgRegisterCounterpartyResponse {
    const NAME: &'static str = "MsgRegisterCounterpartyResponse";
    const PACKAGE: &'static str = "ibc.core.client.v2";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.core.client.v2.MsgRegisterCounterpartyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.core.client.v2.MsgRegisterCounterpartyResponse".into()
    }
}
/// Generated client implementations.
#[cfg(feature = "client")]
pub mod counterparty_msg_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// CounterpartyMsg defines the ibc/client CounterpartyMsg service.
    #[derive(Debug, Clone)]
    pub struct CounterpartyMsgClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "transport")]
    impl CounterpartyMsgClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CounterpartyMsgClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CounterpartyMsgClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CounterpartyMsgClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// RegisterCounterparty defines a rpc handler method for MsgRegisterCounterparty.
        pub async fn register_counterparty(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgRegisterCounterparty>,
        ) -> std::result::Result<
            tonic::Response<super::MsgRegisterCounterpartyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.core.client.v2.CounterpartyMsg/RegisterCounterparty",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.core.client.v2.CounterpartyMsg",
                        "RegisterCounterparty",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "server")]
pub mod counterparty_msg_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CounterpartyMsgServer.
    #[async_trait]
    pub trait CounterpartyMsg: std::marker::Send + std::marker::Sync + 'static {
        /// RegisterCounterparty defines a rpc handler method for MsgRegisterCounterparty.
        async fn register_counterparty(
            &self,
            request: tonic::Request<super::MsgRegisterCounterparty>,
        ) -> std::result::Result<
            tonic::Response<super::MsgRegisterCounterpartyResponse>,
            tonic::Status,
        >;
    }
    /// CounterpartyMsg defines the ibc/client CounterpartyMsg service.
    #[derive(Debug)]
    pub struct CounterpartyMsgServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CounterpartyMsgServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CounterpartyMsgServer<T>
    where
        T: CounterpartyMsg,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/ibc.core.client.v2.CounterpartyMsg/RegisterCounterparty" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterCounterpartySvc<T: CounterpartyMsg>(pub Arc<T>);
                    impl<
                        T: CounterpartyMsg,
                    > tonic::server::UnaryService<super::MsgRegisterCounterparty>
                    for RegisterCounterpartySvc<T> {
                        type Response = super::MsgRegisterCounterpartyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgRegisterCounterparty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CounterpartyMsg>::register_counterparty(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterCounterpartySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CounterpartyMsgServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "ibc.core.client.v2.CounterpartyMsg";
    impl<T> tonic::server::NamedService for CounterpartyMsgServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
